apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: apigw-git
spec:
  type: git
  params:
    - name: revision
      value: master
    - name: url
      value: https://github.com/mismangas/apigw.git
---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: apigw-image-dev
spec:
  type: image
  params:
    - name: url
      value: quay.io/mismangas/apigw:latest
